parameters:
    ongr_settings.filter.pager.request_field: page
    ongr_settings.filter.pager.count_per_page: 15
    ongr_settings.filter.pager.max_pages: 99

    ongr_settings.filter.sort.request_field: sort
    ongr_settings.filter.sort.choices:
        nameAsc:
            label: "Name Asc"
            field: "name"
            order: "asc"
            default: true
        nameDesc:
            label: "Name Desc"
            field: "name"
            order: "desc"
            default: false
        descAsc:
            label: "Description Asc"
            field: "description"
            order: "asc"
            default: true
        descDesc:
            label: "Description Desc"
            field: "description"
            order: "desc"
            default: false
        typeAsc:
            label: "Type Asc"
            field: "type"
            order: "asc"
            default: true
        typeDesc:
            label: "Type Desc"
            field: "type"
            order: "desc"
            default: false

    ongr_settings.filter.match_search.request_field: q
    ongr_settings.filter.match_search.field: "name"

    ongr_settings.filter.single_term.profile.request_field: profile
    ongr_settings.filter.single_term.profile.field: profile

services:
    ongr_settings.filter.pager:
        class: ONGR\FilterManagerBundle\Filter\Widget\Pager\Pager
        calls:
            - ["setRequestField", ["%ongr_settings.filter.pager.request_field%"]]
            - ["setCountPerPage", ["%ongr_settings.filter.pager.count_per_page%"]]
            - ["setMaxPages", ["%ongr_settings.filter.pager.max_pages%"]]

    ongr_settings.filter.sort:
        class: ONGR\FilterManagerBundle\Filter\Widget\Sort\Sort
        calls:
            - ["setRequestField", ["%ongr_settings.filter.sort.request_field%"]]
            - ["setChoices", ["%ongr_settings.filter.sort.choices%"]]

    ongr_settings.filter.match_search:
        class: ONGR\FilterManagerBundle\Filter\Widget\Search\MatchSearch
        calls:
            - ["setRequestField", ["%ongr_settings.filter.match_search.request_field%"]]
            - ["setField", ["%ongr_settings.filter.match_search.field%"]]

    ongr_settings.filter.single_term.profile:
        class: ONGR\FilterManagerBundle\Filter\Widget\Choice\SingleTermChoice
        calls:
            - ["setRequestField", ["%ongr_settings.filter.single_term.profile.request_field%"]]
            - ["setField", ["%ongr_settings.filter.single_term.profile.field%"]]

    ongr_settings.filter_container:
        class: ONGR\FilterManagerBundle\Search\FilterContainer
        calls:
            - ["set", ["pager", "@ongr_settings.filter.pager"]]
            - ["set", ["sort", "@ongr_settings.filter.sort"]]
            - ["set", ["search", "@ongr_settings.filter.match_search"]]
            - ["set", ["profile", "@ongr_settings.filter.single_term.profile"]]
