ongr_settings_home:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ongr_settings_settings
        permanent: true

ongr_settings_profiles:
    path: /profiles
    defaults: { _controller: ONGRSettingsBundle:Profiles:list }

ongr_settings_profiles_get_all:
    path: /profiles/get_all
    defaults: { _controller: ONGRSettingsBundle:Profiles:getProfiles }

ongr_settings_settings:
    path: /settings
    defaults: { _controller: ONGRSettingsBundle:Settings:list }

ongr_settings_settings_create:
    path: /settings/create
    defaults: { _controller: ONGRSettingsBundle:Settings:list }

ongr_settings_settings_update:
    path: /settings/update/{id}
    defaults: { _controller: ONGRSettingsBundle:Settings:update }

ongr_settings_settings_delete:
    path: /settings/delete/{id}
    defaults: { _controller: ONGRSettingsBundle:Settings:delete }

#ongr_settings_profiles_fallback:
#    path: /profiles/{url}
#    defaults: { _controller: ONGRSettingsBundle:Profiles:list, url: null }
#    requirements:
#        url: .*

#ongr_settings_fallback:
#    path: /settings/{url}
#    defaults: { _controller: ONGRSettingsBundle:Settings:list, url: null }
#    requirements:
#        url: .*


ongr_search_page:
    path: /settings/search
    methods:  [GET]
    defaults:
        _controller: ONGRFilterManagerBundle:Manager:json
        managerName: "settings"