ongr_settings_routing_settings:
    resource: "@ONGRSettingsBundle/Resources/config/routing/personal_settings.yml"

ongr_routing_settings:
    resource: "@ONGRSettingsBundle/Resources/config/routing/general_settings.yml"

ongr_settings_settings_add:
    path: /add_setting
    methods: [GET]
    defaults:
        _controller: ONGRSettingsBundle:SettingsAdd:display

ongr_settings_settings_duplicate:
    path: /duplicate_setting/{name}/{profile}
    methods: [GET]
    defaults:
        _controller: ONGRSettingsBundle:SettingsDuplicate:display

ongr_settings_profile_add:
    path: /add_profile
    methods: [GET]
    defaults:
        _controller: ONGRSettingsBundle:Profile:display

ongr_settings_settings_list:
    path:  /{profile}
    methods: [GET]
    defaults:
        _controller: ONGRSettingsBundle:SettingsList:list
        profile: 'default'

ongr_settings_profile_set:
    path: /create/profile
    methods: [POST]
    defaults:
        _controller: ONGRSettingsBundle:Profile:create