parameters:
    # Flash Bag settings
    ongr_settings.flash_bag.cookie.name: ongr_flash_bag

services:
    ongr_settings.flash_bag.flash_bag:
        class: ONGR\SettingsBundle\FlashBag\DirtyFlashBag

    ongr_settings.flash_bag.cookie:
        class: ONGR\CookiesBundle\Cookie\Model\JsonCookie
        arguments: [ %ongr_settings.flash_bag.cookie.name% ]
        tags:
            - { name: ongr_cookie.cookie }

    ongr_settings.flash_bag.cookie.injector:
        class: ONGR\SettingsBundle\EventListener\FlashBagCookieInjectorListener
        arguments: [ "@ongr_settings.flash_bag.flash_bag", "@ongr_settings.flash_bag.cookie" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 96 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
