parameters:
    # Authentication cookie service settings
    ongr_settings.authentication.authentication_cookie.name: ongr_settings_user_auth
    ongr_settings.authentication.authentication_cookie.expiration: P1D # 1 day
    ongr_settings.authentication.authentication_cookie.defaults:
        expires_interval: %ongr_settings.authentication.authentication_cookie.expiration%

    # Signature generator settings
    ongr_settings.authentication.secret: Override%Me

services:
    ongr_settings.authentication.signature_generator:
        class: ONGR\SettingsBundle\Security\Authentication\Cookie\SessionlessSignatureGenerator
        arguments:
            - %ongr_settings.authentication.secret%

    ongr_settings.authentication.authentication_cookie_service:
        class: ONGR\SettingsBundle\Security\Authentication\Cookie\SessionlessAuthenticationCookieService
        arguments:
            - "@ongr_settings.authentication.signature_generator"
            - %ongr_settings.authentication.authentication_cookie.expiration%

    ongr_settings.authentication.authentication_cookie:
        class: ONGR\CookiesBundle\Cookie\Model\JsonCookie
        arguments: [ %ongr_settings.authentication.authentication_cookie.name% ]
        calls:
            - [ setDefaults, [ %ongr_settings.authentication.authentication_cookie.defaults% ] ]
        tags:
            - { name: ongr_cookie.cookie }

    ongr_settings.authentication.sessionless_authentication_provider:
        class: ONGR\SettingsBundle\Security\Authentication\Provider\SessionlessAuthenticationProvider
        arguments:
            - "@ongr_settings.authentication.signature_generator"
            - ""

    ongr_settings.authentication.firewall.listener:
        class: ONGR\SettingsBundle\Security\Authentication\Firewall\SessionlessAuthenticationListener
        arguments:
            - "@security.authentication.manager"
            - "@ongr_settings.authentication.authentication_cookie_service"
            - "@security.token_storage"
            - "@ongr_settings.authentication.authentication_cookie"
