parameters:
    # Image path extension settings
    ongr_settings.twig.image_path_extension.cdn_url: //cdn.ongr.io
    ongr_settings.twig.image_path_extension.image_presets: ~
    ongr_settings.twig.image_path_extension.image_fields_mapping: ~
    ongr_settings.twig.image_path_extension.images_cache_prefix: /cdn

services:
    ongr_settings.twig.setting_extension:
        class: ONGR\SettingsBundle\Twig\GeneralSettingsWidgetExtension
        arguments:
            - "@ongr_settings.settings.personal_settings_manager"
        calls:
            - [ setSettingsContainer, [ "@ongr_settings.settings_container" ] ]
            - [ setLogger, [ "@?logger" ] ]
        tags:
            - { name: "twig.extension" }
            - { name: monolog.logger, channel: admin }

    ongr_settings.twig.personal_settings_extension:
        class: ONGR\SettingsBundle\Twig\PersonalSettingWidgetExtension
        arguments:
            - "@ongr_settings.settings.personal_settings_manager"
        tags:
            - { name: "twig.extension" }

    ongr_settings.twig.encryption_extension:
        class: ONGR\SettingsBundle\Twig\EncryptionExtension
        tags:
            - { name: "twig.extension" }

    ongr_settings.twig.hidden_extension:
            class: ONGR\SettingsBundle\Twig\HiddenExtension
            arguments:
                - "@service_container"
            tags:
                - { name: 'twig.extension' }

    ongr_settings.twig.image_path_extension:
        class: ONGR\SettingsBundle\Twig\ImagePathExtension
        tags:
            - { name: 'twig.extension' }
        arguments:
            - %ongr_settings.twig.image_path_extension.cdn_url%
            -
                'presets': %ongr_settings.twig.image_path_extension.image_presets%
                'mapping': %ongr_settings.twig.image_path_extension.image_fields_mapping%
            - %ongr_settings.twig.image_path_extension.images_cache_prefix%

    ongr_settings.twig.loader_extension:
        class: Twig_Extension_StringLoader
        tags:
            - { name: 'twig.extension' }

    ongr_settings.twig.wrapper_extension:
        class: ONGR\SettingsBundle\Twig\WrapperExtension
        tags:
            - { name: 'twig.extension' }

