sudo: true
language: php
php:
  - 7.0
  - 7.1
  - hhvm
env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"
    - ES_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.2.zip"
matrix:
  allow_failures:
    - php: hhvm
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
  # Container based PHP image ues PHP 5.6.5, once it will be upgraded sudo will be not necessary
  - sudo apt-get install -y oracle-java8-set-default
  - curl -L -o elasticsearch.zip $ES_URL
  - unzip elasticsearch.zip
  - ./elasticsearch-*/bin/elasticsearch -d
before_script:
  - if [[ $TRAVIS_PHP_VERSION != "7.0" ]] && [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - composer install --prefer-dist -n
script:
  - vendor/bin/phpunit --coverage-clover=coveralls.clover
  - vendor/bin/phpcs -p --extensions=php --standard=PSR2 --ignore=vendor/,Tests/app/ ./
after_script:
  - travis_retry php vendor/bin/coveralls
